#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.1.2 effective-5.10 (swiftlang-6.1.2.1.2 clang-1700.0.13.5)
#ifndef CHATSDK_SWIFT_H
#define CHATSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ChatSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

/// The <code>BaseMessage</code> class represents the base message which is generated by a user or an admin.
/// The <code>UserMessage</code>, the <code>FileMessage</code> and the <code>AdminMessage</code> are derived from this class.
SWIFT_CLASS("_TtC7ChatSDK11BaseMessage")
@interface BaseMessage : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC7ChatSDK12AdminMessage")
@interface AdminMessage : BaseMessage
@end

/// An object contains application information
SWIFT_CLASS("_TtC7ChatSDK7AppInfo")
@interface AppInfo : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Represents the options for the Apple Critical Alert.
/// The <code>BaseMessageCreateParams</code> object may have the <code>AppleCriticalAlertOptions</code> object as an <code>appleCriticalAlertOptions</code> property.
/// When the message that has this options is received by the iOS device, the message is displayed as a critical alert.
SWIFT_CLASS("_TtC7ChatSDK25AppleCriticalAlertOptions")
@interface AppleCriticalAlertOptions : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// The <code>ApplicationUserListQuery</code> class is a query class for getting the list of all
/// users of the current application.
/// This instance is created by <code>createApplicationUserListQuery()</code> of <code>GIMChat</code>.
SWIFT_CLASS("_TtC7ChatSDK24ApplicationUserListQuery")
@interface ApplicationUserListQuery : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC7ChatSDK30ApplicationUserListQueryParams")
@interface ApplicationUserListQueryParams : NSObject
/// Default constructor.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface ApplicationUserListQueryParams (SWIFT_EXTENSION(ChatSDK))
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

@interface ApplicationUserListQueryParams (SWIFT_EXTENSION(ChatSDK)) <NSCopying>
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end

/// The <code>BannedUserListQuery</code> class is a query class for getting the list of banned users in
/// a specific channel.
/// This instance is created by <code>createBannedUserListQuery</code> of <code>BaseChannel</code>.
SWIFT_CLASS("_TtC7ChatSDK19BannedUserListQuery")
@interface BannedUserListQuery : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC7ChatSDK25BannedUserListQueryParams")
@interface BannedUserListQueryParams : NSObject
/// Default constructor.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface BannedUserListQueryParams (SWIFT_EXTENSION(ChatSDK))
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

@interface BannedUserListQueryParams (SWIFT_EXTENSION(ChatSDK)) <NSCopying>
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end

/// An object represents base class for channel
SWIFT_CLASS("_TtC7ChatSDK11BaseChannel")
@interface BaseChannel : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface BaseChannel (SWIFT_EXTENSION(ChatSDK))
@property (nonatomic, readonly) NSUInteger hash;
/// Compares this object with given other object.
/// \param object <code>Any</code> instance
///
///
/// returns:
/// <code>true</code> if same otherwise <code>false</code>
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

/// An base object for collection
SWIFT_CLASS("_TtC7ChatSDK14BaseCollection")
@interface BaseCollection : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface BaseMessage (SWIFT_EXTENSION(ChatSDK))
/// Compares this object with given other object.
/// \param object <code>Any</code> instance
///
///
/// returns:
/// <code>true</code> if same otherwise <code>false</code>
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

@class NSString;
@interface BaseMessage (SWIFT_EXTENSION(ChatSDK))
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

/// Represents the base class which has parameters to create a channel.
/// The <code>UserMessageCreateParams</code>, the <code>FileMessageCreateParams</code> are derived from this class.
SWIFT_CLASS("_TtC7ChatSDK23BaseMessageCreateParams")
@interface BaseMessageCreateParams : NSObject
/// Default constructor.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Represents the base class which has parameters to update a message.
/// The <code>UserMessageUpdateParams</code>, the <code>FileMessageUpdateParams</code> are derived from this class.
SWIFT_CLASS("_TtC7ChatSDK23BaseMessageUpdateParams")
@interface BaseMessageUpdateParams : NSObject
/// Default constructor
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// The <code>BlockedUserListQuery</code> class is a query class for getting the list of blocked users
/// by the current user.
/// This instance is created by <code>createBlockedUserListQuery()</code> of <code>GIMChat</code>.
SWIFT_CLASS("_TtC7ChatSDK20BlockedUserListQuery")
@interface BlockedUserListQuery : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface BlockedUserListQuery (SWIFT_EXTENSION(ChatSDK)) <NSCopying>
/// Copies this object
/// \param zone optional <code>NSZone</code>
///
///
/// returns:
/// <code>BlockedUserListQuery</code> instance
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS("_TtC7ChatSDK26BlockedUserListQueryParams")
@interface BlockedUserListQueryParams : NSObject
/// Default constructor.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface BlockedUserListQueryParams (SWIFT_EXTENSION(ChatSDK))
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

@interface BlockedUserListQueryParams (SWIFT_EXTENSION(ChatSDK)) <NSCopying>
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end

/// Channel context
SWIFT_CLASS("_TtC7ChatSDK14ChannelContext")
@interface ChannelContext : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Represents a mesage object that contains a file. Derived from <code>BaseMessage</code>
/// note:
/// This class doesn’t include a binary <em>data</em> for the file. It is just a URL.
SWIFT_CLASS("_TtC7ChatSDK11FileMessage")
@interface FileMessage : BaseMessage
@end

@interface FileMessage (SWIFT_EXTENSION(ChatSDK))
/// Compares this object with given other object.
/// \param object <code>Any</code> instance
///
///
/// returns:
/// <code>true</code> if same otherwise <code>false</code>
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

/// An object contains set of options to create <code>FileMessage</code>.
SWIFT_CLASS("_TtC7ChatSDK23FileMessageCreateParams")
@interface FileMessageCreateParams : BaseMessageCreateParams
/// Default constructor.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// The <code>FileMessageUpdateParams</code> class is used to update a file message in <code>BaseChannel</code>. This is a child class of <code>BaseMessageUpdateParams</code>.
SWIFT_CLASS("_TtC7ChatSDK23FileMessageUpdateParams")
@interface FileMessageUpdateParams : BaseMessageUpdateParams
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// The <code>GIMChat</code> is the core class for GIMChat. This class is singletone instance which is initialized by Application ID.
/// This class provides the methods for overall operations. The methods include <code>BaseChannelDelegate</code> registration for receiving events
/// that are related to channels, <code>ConnectionDelegate</code> for managing the connection status, updating the current user’s information,
/// registration for APNS push notification and blocking other users.
SWIFT_CLASS("_TtC7ChatSDK7GIMChat")
@interface GIMChat : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Represents GIMChatChat options.
SWIFT_CLASS("_TtC7ChatSDK14GIMChatOptions")
@interface GIMChatOptions : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSCoder;
/// Sendbird error class.
SWIFT_CLASS("_TtC7ChatSDK8GIMError")
@interface GIMError : NSError
/// Create error object
/// \param domin domain.
///
/// \param code error code.
///
/// \param dict additional info in dictionary
///
- (nonnull instancetype)initWithDomain:(NSString * _Nonnull)domain code:(NSInteger)code userInfo:(NSDictionary<NSString *, id> * _Nullable)dict OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end

/// The <code>GroupChannel</code> class represents a group channel which is a private chat.
/// The user who wants to join the group channel has to be invited by another user who is already joined
/// the channel. This class is derived from <code>BaseChannel</code>. If the <code>BaseChannelDelegate</code> is added,
/// the user will automatically receive all messages from the group channels where the user belongs after
/// connection. The <code>GroupChannel</code> provides the features of general messaging apps.
/// <ul>
///   <li>
///     Typing indicator.
///   </li>
///   <li>
///     Read status for each message.
///   </li>
///   <li>
///     Unread message count in the channel.
///   </li>
///   <li>
///     Lastest message in the channel.
///   </li>
/// </ul>
/// The <code>GroupChannel</code> has a special property, <code>isDistinct</code>. The distinct property enabled group
/// channel is always reuesd for same channel <em>members</em>. If a new member gets invited or the member
/// left from the channel, then the distinct property disabled automatically. If you don’t set distinct property
/// on the channel, it always create new channel for the same <em>members</em>.
SWIFT_CLASS("_TtC7ChatSDK12GroupChannel")
@interface GroupChannel : BaseChannel
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// An object that accesses the cache for the group channels.
SWIFT_CLASS("_TtC7ChatSDK22GroupChannelCollection")
@interface GroupChannelCollection : BaseCollection
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// An object contains set of options to create a group channel
SWIFT_CLASS("_TtC7ChatSDK24GroupChannelCreateParams")
@interface GroupChannelCreateParams : NSObject
/// Default constructor.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface GroupChannelCreateParams (SWIFT_EXTENSION(ChatSDK)) <NSCopying>
/// Copies this object
/// \param zone optional <code>NSZone</code>
///
///
/// returns:
/// <code>GroupChannelParams</code> instance
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end

/// The <code>GroupChannelListQuery</code> class is a query class for getting the list of group channels.
/// The instance of this class is created by <code>createMyGroupChannelListQuery()</code> in <code>GroupChannel</code> class.
SWIFT_CLASS("_TtC7ChatSDK21GroupChannelListQuery")
@interface GroupChannelListQuery : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC7ChatSDK27GroupChannelListQueryParams")
@interface GroupChannelListQueryParams : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface GroupChannelListQueryParams (SWIFT_EXTENSION(ChatSDK))
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

/// An object contains set of options to retrieve total unread channel count
SWIFT_CLASS("_TtC7ChatSDK41GroupChannelTotalUnreadChannelCountParams")
@interface GroupChannelTotalUnreadChannelCountParams : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// An object contains a set of options to get total unread message count from a group channel
SWIFT_CLASS("_TtC7ChatSDK41GroupChannelTotalUnreadMessageCountParams")
@interface GroupChannelTotalUnreadMessageCountParams : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// An object contains a set of options to update a group channel
SWIFT_CLASS("_TtC7ChatSDK24GroupChannelUpdateParams")
@interface GroupChannelUpdateParams : NSObject
/// Default constructor.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// An object to initialize GIMChat
SWIFT_CLASS("_TtC7ChatSDK10InitParams")
@interface InitParams : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// The <code>User</code> class represents a user. The user is identified by the <code>userId</code>, so the <code>userId</code> has
/// to be unique. The <code>userId</code>, <code>nickname</code> and <code>profileURL</code> are valid in every <code>User</code>
/// instance, however the <code>connectionStatus</code> and <code>lastSeenAt</code> is valid in <code>User</code> instance
/// from <code>UserListQuery</code>.
SWIFT_CLASS("_TtC7ChatSDK4User")
@interface User : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Represents a member in <code>GroupChannel</code>
SWIFT_CLASS("_TtC7ChatSDK6Member")
@interface Member : User
@end

/// The <code>MemberListQuery</code> class is a query class for getting the list member in group channels.
/// The instance of this class is created by <code>createMemberListQuery()</code> in <code>GroupChannel</code> class.
SWIFT_CLASS("_TtC7ChatSDK15MemberListQuery")
@interface MemberListQuery : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface MemberListQuery (SWIFT_EXTENSION(ChatSDK)) <NSCopying>
/// Copies this object
/// \param zone optional <code>NSZone</code>
///
///
/// returns:
/// <code>MemberListQuery</code> instance
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS("_TtC7ChatSDK21MemberListQueryParams")
@interface MemberListQueryParams : NSObject
/// Default constructor.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface MemberListQueryParams (SWIFT_EXTENSION(ChatSDK))
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

@interface MemberListQueryParams (SWIFT_EXTENSION(ChatSDK)) <NSCopying>
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end

/// An object contains set of options for message change logs.
SWIFT_CLASS("_TtC7ChatSDK23MessageChangeLogsParams")
@interface MessageChangeLogsParams : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// An object that accesses the cache for the messages.
SWIFT_CLASS("_TtC7ChatSDK17MessageCollection")
@interface MessageCollection : BaseCollection
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Represents what happened to the messages.
SWIFT_CLASS("_TtC7ChatSDK14MessageContext")
@interface MessageContext : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// An object contains set of options for get message methods
SWIFT_CLASS("_TtC7ChatSDK17MessageListParams")
@interface MessageListParams : NSObject <NSCopying>
/// Copies this object
/// \param zone optional <code>NSZone</code>
///
///
/// returns:
/// <code>MessageListParams</code> instance
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface MessageListParams (SWIFT_EXTENSION(ChatSDK))
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

/// The <code>MessageMetaArray</code> instance has a string type of key and an array type of value.
/// The value consists of a string.
/// It usually can be used for ‘vote’ or ‘reaction’ for the message.
SWIFT_CLASS("_TtC7ChatSDK16MessageMetaArray")
@interface MessageMetaArray : NSObject <NSCopying>
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface MessageMetaArray (SWIFT_EXTENSION(ChatSDK))
/// Compares this object with given other object.
/// \param object <code>Any</code> instance
///
///
/// returns:
/// <code>true</code> if same otherwise <code>false</code>
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
/// Copies this object
/// \param zone optional <code>NSZone</code>
///
///
/// returns:
/// <code>MessageMetaArray</code> instance
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS("_TtC7ChatSDK19MessageRequestState")
@interface MessageRequestState : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// An object contains set of options to retrieve a message.
SWIFT_CLASS("_TtC7ChatSDK22MessageRetrievalParams")
@interface MessageRetrievalParams : NSObject <NSCopying>
/// Default constructor.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Copies this object
/// \param zone optional <code>NSZone</code>
///
///
/// returns:
/// <code>MessageRetrievalParams</code> instance
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end

/// A class representing query to retrieve list of <code>BaseMessage</code>s that matches a given
/// query with given filters. <code>MessageSearchQuery</code> can be generated by using
/// <code>MessageSearchQueryBuilder</code>
SWIFT_CLASS("_TtC7ChatSDK18MessageSearchQuery")
@interface MessageSearchQuery : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface MessageSearchQuery (SWIFT_EXTENSION(ChatSDK)) <NSCopying>
/// Copies this object
/// \param zone optional <code>NSZone</code>
///
///
/// returns:
/// <code>MessageListQuery</code> instance
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end

/// Message search query builder
SWIFT_CLASS("_TtC7ChatSDK24MessageSearchQueryParams")
@interface MessageSearchQueryParams : NSObject
/// Default constructor
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface MessageSearchQueryParams (SWIFT_EXTENSION(ChatSDK))
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

@interface MessageSearchQueryParams (SWIFT_EXTENSION(ChatSDK)) <NSCopying>
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end

/// Represents a mesage object that contains a file. Derived from <code>BaseMessage</code>
/// note:
/// This class doesn’t include a binary <em>data</em> for the file. It is just a URL.
SWIFT_CLASS("_TtC7ChatSDK20MultipleFilesMessage")
@interface MultipleFilesMessage : BaseMessage
@end

@interface MultipleFilesMessage (SWIFT_EXTENSION(ChatSDK))
/// Compares this object with given other object.
/// \param object <code>Any</code> instance
///
///
/// returns:
/// <code>true</code> if same otherwise <code>false</code>
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

/// The <code>MutedUserListQuery</code> class is a query class for getting the list of muted users in
/// a specific channel.
/// This instance is created by <code>createMutedUserListQuery</code> of <code>BaseChannel</code>.
SWIFT_CLASS("_TtC7ChatSDK18MutedUserListQuery")
@interface MutedUserListQuery : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC7ChatSDK24MutedUserListQueryParams")
@interface MutedUserListQueryParams : NSObject
/// Default constructor.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface MutedUserListQueryParams (SWIFT_EXTENSION(ChatSDK))
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

@interface MutedUserListQueryParams (SWIFT_EXTENSION(ChatSDK)) <NSCopying>
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end

/// Represents OpenGraph Image information
SWIFT_CLASS("_TtC7ChatSDK7OGImage")
@interface OGImage : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Represents OpenGraph information
SWIFT_CLASS("_TtC7ChatSDK10OGMetaData")
@interface OGMetaData : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// The <code>OpenChannel</code> class represents a open channel which is a public chat.
/// Any users who wants to enter the channel can join freely. This class is derived from <code>BaseChannel</code>.
/// If the <code>OpenChannelDelegate</code> is added, the user will automatically receive all messages from the
/// channels where the user belongs after connection. The <code>OpenChannel</code> does not provide the features that
/// <code>OpenChannel</code> does, but it can handle much more users.
SWIFT_CLASS("_TtC7ChatSDK11OpenChannel")
@interface OpenChannel : BaseChannel
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// The <code>OpenChannelCreateParams</code> class contain parameters for <code>open channel</code>.
/// When you want to create a open channel or update a open channel, use this class. Add what you want
/// to create with, add which properties you want to update, and pass this class to <code>OpenChannel</code>. You
/// can use this class with apis that are <code>OpenChannel.createChannel(params::completionHandler:)</code> or
/// <code>OpenChannel,update(params:completionHandler:)</code>.
SWIFT_CLASS("_TtC7ChatSDK23OpenChannelCreateParams")
@interface OpenChannelCreateParams : NSObject <NSCopying>
- (nonnull instancetype)init;
/// Copies this object
/// \param zone optional <code>NSZone</code>
///
///
/// returns:
/// <code>OpenChannelParams</code> instance
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end

/// The <code>OpenChannelListQuery</code> class is a query class for getting the list of open channels.
/// The instance of this class is created by <code>createOpenChannelListQuery()</code> in <code>OpenChannel</code> class.
SWIFT_CLASS("_TtC7ChatSDK20OpenChannelListQuery")
@interface OpenChannelListQuery : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC7ChatSDK26OpenChannelListQueryParams")
@interface OpenChannelListQueryParams : NSObject
/// Default constructor.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface OpenChannelListQueryParams (SWIFT_EXTENSION(ChatSDK))
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

/// An object contains set of options to update open channel
SWIFT_CLASS("_TtC7ChatSDK23OpenChannelUpdateParams")
@interface OpenChannelUpdateParams : NSObject <NSCopying>
/// Default constructor
- (nonnull instancetype)init;
/// Copies this object
/// \param zone optional <code>NSZone</code>
///
///
/// returns:
/// <code>OpenChannelUpdateParams</code> instance
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end

/// The <code>OperatorListQuery</code> class is a query class for getting the list of operators in channel.
/// The instance of this class is created by <code>createOperatorListQuery()</code> in <code>BaseChannel</code> class.
SWIFT_CLASS("_TtC7ChatSDK17OperatorListQuery")
@interface OperatorListQuery : NSObject
/// Copies this object
/// \param zone optional <code>NSZone</code>
///
///
/// returns:
/// <code>OperatorListQuery</code> instance
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface OperatorListQuery (SWIFT_EXTENSION(ChatSDK)) <NSCopying>
@end

SWIFT_CLASS("_TtC7ChatSDK23OperatorListQueryParams")
@interface OperatorListQueryParams : NSObject
/// Default constructor.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface OperatorListQueryParams (SWIFT_EXTENSION(ChatSDK))
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

@interface OperatorListQueryParams (SWIFT_EXTENSION(ChatSDK)) <NSCopying>
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end

/// The <code>ParticipantListQuery</code> class is a query class for getting the list of participants in
/// an open channel.
/// This instance is created by <code>createParticipantListQuery()</code> of <code>OpenChannel</code>.
SWIFT_CLASS("_TtC7ChatSDK20ParticipantListQuery")
@interface ParticipantListQuery : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface ParticipantListQuery (SWIFT_EXTENSION(ChatSDK)) <NSCopying>
/// Copies this object
/// \param zone optional <code>NSZone</code>
///
///
/// returns:
/// <code>ParticipantListQuery</code> instance
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS("_TtC7ChatSDK26ParticipantListQueryParams")
@interface ParticipantListQueryParams : NSObject
/// Default constructor.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface ParticipantListQueryParams (SWIFT_EXTENSION(ChatSDK))
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

@interface ParticipantListQueryParams (SWIFT_EXTENSION(ChatSDK)) <NSCopying>
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end

/// An object which retrieves messages from the given channel.
/// The instance of this class is created by <code>createPinnedMessageListQuery()</code> in <code>BaseChannel</code> class.
SWIFT_CLASS("_TtC7ChatSDK22PinnedMessageListQuery")
@interface PinnedMessageListQuery : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC7ChatSDK28PinnedMessageListQueryParams")
@interface PinnedMessageListQueryParams : NSObject
/// Default constructor.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface PinnedMessageListQueryParams (SWIFT_EXTENSION(ChatSDK)) <NSCopying>
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end

/// A object to represent a plugin
SWIFT_CLASS("_TtC7ChatSDK6Plugin")
@interface Plugin : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Represents a poll that users can vote
SWIFT_CLASS("_TtC7ChatSDK4Poll")
@interface Poll : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface Poll (SWIFT_EXTENSION(ChatSDK))
/// Compares this object with given other object.
/// \param object <code>Any</code> instance
///
///
/// returns:
/// <code>true</code> if same otherwise <code>false</code>
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

/// Represents a parameter object to create or update poll object
SWIFT_CLASS("_TtC7ChatSDK16PollCreateParams")
@interface PollCreateParams : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Represents a poll data
SWIFT_CLASS("_TtC7ChatSDK8PollData")
@interface PollData : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Represents a poll details information
SWIFT_CLASS("_TtC7ChatSDK11PollDetails")
@interface PollDetails : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface PollDetails (SWIFT_EXTENSION(ChatSDK))
/// Compares this object with given other object.
/// \param object <code>Any</code> instance
///
///
/// returns:
/// <code>true</code> if same otherwise <code>false</code>
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

/// An object to retrieve list of <code>Poll</code>
SWIFT_CLASS("_TtC7ChatSDK13PollListQuery")
@interface PollListQuery : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Represents an option for poll
SWIFT_CLASS("_TtC7ChatSDK10PollOption")
@interface PollOption : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface PollOption (SWIFT_EXTENSION(ChatSDK))
/// Compares this object with given other object.
/// \param object <code>Any</code> instance
///
///
/// returns:
/// <code>true</code> if same otherwise <code>false</code>
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

/// An object that retrieves a specific poll option.
SWIFT_CLASS("_TtC7ChatSDK25PollOptionRetrievalParams")
@interface PollOptionRetrievalParams : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// An object contains a voter result for an option
SWIFT_CLASS("_TtC7ChatSDK21PollOptionVoterResult")
@interface PollOptionVoterResult : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// An object contains set of options to retrieve <code>Poll</code> object
SWIFT_CLASS("_TtC7ChatSDK19PollRetrievalParams")
@interface PollRetrievalParams : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Represents an poll update event
SWIFT_CLASS("_TtC7ChatSDK15PollUpdateEvent")
@interface PollUpdateEvent : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// An object contains set of options to update <code>Poll</code>
SWIFT_CLASS("_TtC7ChatSDK16PollUpdateParams")
@interface PollUpdateParams : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Represents a vote event on a poll
SWIFT_CLASS("_TtC7ChatSDK13PollVoteEvent")
@interface PollVoteEvent : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// An object to retrieve list of voter
SWIFT_CLASS("_TtC7ChatSDK18PollVoterListQuery")
@interface PollVoterListQuery : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// This object is used when calling voterList query.
SWIFT_CLASS("_TtC7ChatSDK24PollVoterListQueryParams")
@interface PollVoterListQueryParams : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// An object which retrieves messages from the given channel.
/// The instance of this class is created by <code>createPreviousMessageListQuery()</code> in <code>BaseChannel</code> class.
SWIFT_CLASS("_TtC7ChatSDK24PreviousMessageListQuery")
@interface PreviousMessageListQuery : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC7ChatSDK30PreviousMessageListQueryParams")
@interface PreviousMessageListQueryParams : NSObject
/// Default constructor.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface PreviousMessageListQueryParams (SWIFT_EXTENSION(ChatSDK))
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

@interface PreviousMessageListQueryParams (SWIFT_EXTENSION(ChatSDK)) <NSCopying>
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end

/// A object represents the reaction info.
/// The <code>BaseMessage</code> object can have the <code>Reaction</code> object in <code>reactions</code> property.
SWIFT_CLASS("_TtC7ChatSDK8Reaction")
@interface Reaction : NSObject
/// hash
@property (nonatomic, readonly) NSUInteger hash;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// An object represents reaction event info.
/// The object is returned by not only the completion handler of <code>addReaction(message:key:completionHandler:)</code>
/// and <code>deleteReaction(message:key:completionHandler:)</code> in <code>BaseChannel</code> class but also
/// <code>channel(_:updatedReaction:)</code> delegate of <code>BaseChannelDelegate</code> protocol. The object has
/// to be applied to the message that has the identical message ID with the <code>apply(_:)</code> method in <code>BaseMessage</code> class.
SWIFT_CLASS("_TtC7ChatSDK13ReactionEvent")
@interface ReactionEvent : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// An object represents read status of a user
SWIFT_CLASS("_TtC7ChatSDK10ReadStatus")
@interface ReadStatus : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Represents a user who has been restricted in a channel
SWIFT_CLASS("_TtC7ChatSDK14RestrictedUser")
@interface RestrictedUser : User
@end

/// An object contains information about restriction
SWIFT_CLASS("_TtC7ChatSDK15RestrictionInfo")
@interface RestrictionInfo : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// A base class to create a scheduled message.
SWIFT_CLASS("_TtC7ChatSDK32ScheduledBaseMessageCreateParams")
@interface ScheduledBaseMessageCreateParams : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// A base class to update a scheduled message.
SWIFT_CLASS("_TtC7ChatSDK32ScheduledBaseMessageUpdateParams")
@interface ScheduledBaseMessageUpdateParams : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Class holding an information about the scheduled messages.
SWIFT_CLASS("_TtC7ChatSDK13ScheduledInfo")
@interface ScheduledInfo : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// The <code>ScheduledMessageListQuery</code> class is a query class for getting the list of scheduled messages.
SWIFT_CLASS("_TtC7ChatSDK25ScheduledMessageListQuery")
@interface ScheduledMessageListQuery : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface ScheduledMessageListQuery (SWIFT_EXTENSION(ChatSDK)) <NSCopying>
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS("_TtC7ChatSDK31ScheduledMessageListQueryParams")
@interface ScheduledMessageListQueryParams : NSObject
/// Default constructor.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface ScheduledMessageListQueryParams (SWIFT_EXTENSION(ChatSDK))
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

@interface ScheduledMessageListQueryParams (SWIFT_EXTENSION(ChatSDK)) <NSCopying>
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end

/// An object that contains a set of options to retrieve scheduled messages.
SWIFT_CLASS("_TtC7ChatSDK31ScheduledMessageRetrievalParams")
@interface ScheduledMessageRetrievalParams : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// An object that has parameters to create a scheduled message.
SWIFT_CLASS("_TtC7ChatSDK32ScheduledUserMessageCreateParams")
@interface ScheduledUserMessageCreateParams : ScheduledBaseMessageCreateParams
@end

/// An object that has parameters to update a scheduled message.
SWIFT_CLASS("_TtC7ChatSDK32ScheduledUserMessageUpdateParams")
@interface ScheduledUserMessageUpdateParams : ScheduledBaseMessageUpdateParams
/// Initializes and returns a params object for updating a scheduled user message.
///
/// returns:
/// An initialized scheduled user message params.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Represents a user that typically binds with message
SWIFT_CLASS("_TtC7ChatSDK6Sender")
@interface Sender : User
@end

/// An object that represents the information about threaded messages, whose properties show how many
/// replies the thread has received, who left the replies, and when the last reply was added.
SWIFT_CLASS("_TtC7ChatSDK10ThreadInfo")
@interface ThreadInfo : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// An object that is returned through the event handler when a threaded reply is added or deleted.
/// This object should be applied to the parent message.
SWIFT_CLASS("_TtC7ChatSDK21ThreadInfoUpdateEvent")
@interface ThreadInfoUpdateEvent : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// An object contains set of options to retrieve threaded messages.
SWIFT_CLASS("_TtC7ChatSDK25ThreadedMessageListParams")
@interface ThreadedMessageListParams : NSObject <NSCopying>
/// Copies this object.
/// \param zone optional <code>NSZone</code>
///
///
/// returns:
/// <code>ThreadedMessageListParams</code> instance
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Represents a thumbnail information
SWIFT_CLASS("_TtC7ChatSDK9Thumbnail")
@interface Thumbnail : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface Thumbnail (SWIFT_EXTENSION(ChatSDK))
/// Compares this object with given other object.
/// \param object <code>Any</code> instance
///
///
/// returns:
/// <code>true</code> if same otherwise <code>false</code>
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

/// The <code>ThumbnailSize</code> class represents the thumbnail size of thumbnail.
SWIFT_CLASS("_TtC7ChatSDK13ThumbnailSize")
@interface ThumbnailSize : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// An object that contains a set of options to get scheduled messages count.
SWIFT_CLASS("_TtC7ChatSDK32TotalScheduledMessageCountParams")
@interface TotalScheduledMessageCountParams : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC7ChatSDK11UpdatedPoll")
@interface UpdatedPoll : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// An object contains information about updated vote count
SWIFT_CLASS("_TtC7ChatSDK16UpdatedVoteCount")
@interface UpdatedVoteCount : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Represents a mesage object that contains a text message. Derived from <code>BaseMessage</code>.
SWIFT_CLASS("_TtC7ChatSDK11UserMessage")
@interface UserMessage : BaseMessage
@end

/// An object contains a set of options to create <code>UserMessage</code>.
SWIFT_CLASS("_TtC7ChatSDK23UserMessageCreateParams")
@interface UserMessageCreateParams : BaseMessageCreateParams
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// The <code>UserMessageUpdateParams</code> class is used to update a user message in <code>BaseChannel</code>. This is a child class of <code>BaseMessageUpdateParams</code>.
/// since:
/// 4.0.0
SWIFT_CLASS("_TtC7ChatSDK23UserMessageUpdateParams")
@interface UserMessageUpdateParams : BaseMessageUpdateParams
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// An object to update user information
SWIFT_CLASS("_TtC7ChatSDK16UserUpdateParams")
@interface UserUpdateParams : NSObject
/// Default constructor.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_EXTERN void ChatSDK_Connect(char const * _Nullable userId, char const * _Nullable authToken, int32_t callbackId) SWIFT_NOEXCEPT;

SWIFT_EXTERN void ChatSDK_CreateGroupChannel(char const * _Nullable channelName, char const * _Nullable userIdsJson, char const * _Nullable operatorUserIdsJson, BOOL isDistinct, int32_t callbackId) SWIFT_NOEXCEPT;

SWIFT_EXTERN void ChatSDK_Initialize(char const * _Nonnull appId) SWIFT_NOEXCEPT;

SWIFT_EXTERN void ChatSDK_InviteUsers(char const * _Nullable channelUrl, char const * _Nullable userIdsJson, int32_t callbackId) SWIFT_NOEXCEPT;

SWIFT_EXTERN void ChatSDK_ResetConfiguration(void) SWIFT_NOEXCEPT;

SWIFT_EXTERN void ChatSDK_SendMessage(char const * _Nullable channelUrl, char const * _Nullable messagePtr, int32_t callbackId) SWIFT_NOEXCEPT;

SWIFT_EXTERN void ChatSDK_SetCallback(void (* _Nullable callback)(int32_t, char const * _Nullable, char const * _Nullable)) SWIFT_NOEXCEPT;

SWIFT_EXTERN void ChatSDK_SetConfiguration(char const * _Nullable appId, char const * _Nullable domain) SWIFT_NOEXCEPT;

SWIFT_EXTERN void ChatSDK_SetMessageCallback(void (* _Nullable callback)(char const * _Nullable, char const * _Nullable)) SWIFT_NOEXCEPT;

@interface User (SWIFT_EXTENSION(ChatSDK))
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

@interface User (SWIFT_EXTENSION(ChatSDK))
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

@interface UserMessage (SWIFT_EXTENSION(ChatSDK))
/// Compares this object with given other object.
/// \param object <code>Any</code> instance
///
///
/// returns:
/// <code>true</code> if same otherwise <code>false</code>
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
